import { type NextPage } from "next";
import Head from "next/head";

import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Twitting</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {/* <SignInButton mode="modal">
          <button className="btn-primary btn">Sign in</button>
        </SignInButton> */}
        {!user.isSignedIn && (
          <SignInButton mode="modal">
            <button className="btn-primary btn">Sign In</button>
          </SignInButton>
        )}
        {!!user.isSignedIn && (
          <SignOutButton>
            <button className="btn-primary btn">Sign Out</button>
          </SignOutButton>
        )}
      </main>
    </>
  );
};

export default Home;
